const { ActionRowBuilder, ButtonBuilder, ButtonStyle } = require('discord.js');

function createPokeBallButtons(userData, encounterId) {
    return new ActionRowBuilder()
            .addComponents(
                        new ButtonBuilder()
                                        .setCustomId(`catch_pokeball_${encounterId}`)
                                                        .setLabel(`Pokeball`)
                                                                        .setEmoji('1259115461770084457')
                                                                                        .setStyle(ButtonStyle.Primary)
                                                                                                        .setDisabled(!userData.items.pokeball || userData.items.pokeball <= 0),
                                                                                                                    new ButtonBuilder()
                                                                                                                                    .setCustomId(`catch_greatball_${encounterId}`)
                                                                                                                                                    .setLabel(`Greatball`)
                                                                                                                                                                    .setEmoji('1259115641080643657')
                                                                                                                                                                                    .setStyle(ButtonStyle.Primary)
                                                                                                                                                                                                    .setDisabled(!userData.items.greatball || userData.items.greatball <= 0),
                                                                                                                                                                                                                new ButtonBuilder()
                                                                                                                                                                                                                                .setCustomId(`catch_ultraball_${encounterId}`)
                                                                                                                                                                                                                                                .setLabel(`Ultraball`)
                                                                                                                                                                                                                                                                .setEmoji('1259115187990958090')
                                                                                                                                                                                                                                                                                .setStyle(ButtonStyle.Primary)
                                                                                                                                                                                                                                                                                                .setDisabled(!userData.items.ultraball || userData.items.ultraball <= 0),
                                                                                                                                                                                                                                                                                                            new ButtonBuilder()
                                                                                                                                                                                                                                                                                                                            .setCustomId(`catch_masterball_${encounterId}`)
                                                                                                                                                                                                                                                                                                                                            .setLabel(`Masterball`)
                                                                                                                                                                                                                                                                                                                                                            .setEmoji('1259115795317784627')
                                                                                                                                                                                                                                                                                                                                                                            .setStyle(ButtonStyle.Primary)
                                                                                                                                                                                                                                                                                                                                                                                            .setDisabled(!userData.items.masterball || userData.items.masterball <= 0)
                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                    module.exports = { createPokeBallButtons };